from django.urls import path
from . import views
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('api/register', views.user_registration_api_view, name='register_api_view'), # API view for users to create an account
    path('register', views.user_registration_view, name='register_view'), # HTML view for users to create an account
    path('api/users', views.all_users_api_view, name='all_users_api_view'), # API view to display users
    path('users', views.all_users_view, name='all_users_view'), # HTML view to display users
    path('api/user', views.user_details_api_view, name='user_details_api_view'), # API view to display and update user details
    path('user', views.user_details_view, name='user_details_view'), # HTML view to display and update user details
    path('api/token', obtain_auth_token, name='api-token-auth'), # API view so user can log in to generate auth tokens
    # path('token', views.obtain_auth_token_view, name='token_view'), # HTML view so users can log in to generate auth tokens, if you uncomment out this, comment out below path
    path('accounts/login', views.CustomLoginView.as_view(), name='login_view'), # Django's built-in login view (HTML), keeps user authenticated while session is valid, if you comment out this, uncomment out above path
    path('accounts/logout', views.CustomLogoutView.as_view(), name='logout_view'), # Django's built-in logout view (HTML)
    path('api/logger', views.logger_api_view, name='logger_api_view'), # API view for employees to log/view hours
    path('logger', views.logger_view, name='logger_view'), # AJAX view for employees to log/view hours
    path('api/log-details', views.log_details_api_view, name='log_details_api_view'), # API view for employees to view their log details
    path('log-details', views.log_details_view, name='log_details_view'), # HTML view for employees to view their log details
    path('', views.index, name='index'), # Home page (HTML)
    path('api/search', views.search_api_view, name='search_api_view'), # API view to search MenuItems and Categories
    path('search', views.search_view, name='search_view'), # HTML view to search MenuItems and Categories
    path('api/comments', views.comments_api_view, name='comments_api_view'), # API view for comments about restaurant
    path('comments', views.comments_view, name='comments_view'), # HTML view for comments about restaurant
    path('api/groups/employee/users', views.employee_api_view, name='employee_api_view'), # API view to display/add users to Employee group
    path('groups/employee/users', views.employee_view, name='employee_view'), # HTML view to display/add users to Employee group
    path('api/groups/employee/users/delete', views.employee_delete_api_view, name='employee_delete_api_view'), # API view to remove users from Employee group
    path('groups/employee/users/delete', views.employee_delete_view, name='employee_delete_view'), # HTML view to remove users from Employee group
    path('api/groups/manager/users', views.manager_api_view, name='manager_api_view'), # API view to display/add users to Manager group
    path('groups/manager/users', views.manager_view, name='manager_view'), # HTML view to display/add users to Manager group
    path('api/groups/manager/users/delete', views.manager_delete_api_view, name='manager_delete_api_view'), # API view to remove users from Manager group
    path('groups/manager/users/delete', views.manager_delete_view, name='manager_delete_view'), # HTML view to remove users from Manager group
    path('api/groups/delivery-crew/users', views.delivery_crew_api_view, name='delivery_crew_api_view'), # API view to display/add users to Delivery Crew group
    path('groups/delivery-crew/users', views.delivery_crew_view, name='delivery_crew_view'), # HTML view to display/add users to Delivery Crew group
    path('api/groups/delivery-crew/users/delete', views.delivery_crew_delete_api_view, name='delivery_crew_delete_api_view'), # API view to remove users from Delivery Crew group
    path('groups/delivery-crew/users/delete', views.delivery_crew_delete_view, name='delivery_crew_delete_view'), # HTML view to remove users from Delivery Crew group
    path('api/categories', views.categories_api_view, name='categories_api_view'), # API view to display/add categories
    path('categories', views.categories_view, name='categories_view'), # HTML view to display/add categories
    path('api/category/delete', views.category_delete_api_view, name='category_delete_api_view'), # API view to delete categories
    path('category/delete', views.category_delete_view, name='category_delete_view'), # HTML view to delete categories
    path('api/category', views.category_details_api_view, name='category_details_api_view'), # API view to display menu items in category
    path('category', views.category_details_view, name='category_details_view'), # HTML view to display menu items in category
    path('api/menu', views.menu_api_view, name='menu_api_view'), # API view to display menu/add menu items
    path('menu', views.menu_view, name='menu_view'), # HTML view to display menu/add menu items
    path('api/menu-item', views.menu_item_api_view, name='menu_item_api_view'), # API view to display individual menu items
    path('menu-item', views.menu_item_view, name='menu_item_view'), # HTML view to display individual menu items
    path('api/menu-item/delete', views.menu_item_delete_api_view, name='menu_item_delete_api_view'), # API view to delete menu items
    path('menu-item/delete', views.menu_item_delete_view, name='menu_item_delete_view'), # HTML view to delete menu items
    path('api/cart', views.cart_api_view, name='cart_api_view'), # API view to display, add, delete items in user cart
    path('cart', views.cart_view, name='cart_view'), # HTML view to display, update, delete items in user cart
    path('api/orders', views.orders_api_view, name='orders_api_view'), # API view to display and create orders
    path('orders', views.orders_view, name='orders_view'), # HTML view to display and create orders
    path('api/order', views.order_details_api_view, name='order_details_api_view'), # API view to display, update, and delete orders
    path('order', views.order_details_view, name='order_details_view'), # HTML view to display, update, and delete orders
    path('api/booking', views.booking_api_view, name='booking_api_view'), # API view for users to book a reservation
    path('booking', views.booking_view, name='booking_view'), # HTML view for users to book a reservation
    path('api/reservations', views.reservations_api_view, name='reservations_api_view'), # API view to display current reservations
    path('reservations', views.reservations_view, name='reservations_view'), # HTML view to display current reservations
    path('api/reservations/old', views.old_reservations_api_view, name='old_reservations_api_view'), # API view to display past reservations
    path('reservations/old', views.old_reservations_view, name='old_reservations_view'), # HTML view to display past reservations
    path('api/reservation', views.reservation_details_api_view, name='reservation_details_api_view'), # API view to display reservation details, update, and delete reservations
    path('reservation', views.reservation_details_view, name='reservation_details_view'), # HTML view to display reservation details, update, and delete reservations
]