# Generated by Django 5.0.6 on 2024-05-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_category_slug_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='log_type',
            field=models.CharField(choices=[('IN', 'Login'), ('OUT', 'Logout')], default='IN', max_length=3),
        ),
    ]
