# Generated by Django 5.0.6 on 2024-05-31 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_logger_log_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='time',
        ),
    ]
