# Generated by Django 5.0.6 on 2024-06-23 22:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_rename_date_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
