# Generated by Django 5.0.6 on 2024-07-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_usercomments_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('completed', 'Completed'), ('missed', 'Missed')], default='current', max_length=10),
        ),
    ]
