# Generated by Django 5.0.6 on 2024-07-22 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='status',
            new_name='reservation_status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
    ]
