# Generated by Django 5.0.6 on 2024-07-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
    ]
